title: INPUT A TITLE HERE
authors:
  - name: Jakub Opršal
    email: jakub.oprsal@ist.ac.at
    affiliation:
      institution: Institute of Science and Technology Austria
      city: Klosterneuburg
      country: Austria
    orcid: 0000-0003-1245-3456

funding:
  - agency: Marie Skłodowska-Curie Action
    number: 101034413
    scheme: European Union's Horizon 2020
    note: >-
      This project has received funding from the European Union’s Horizon 2020 research and innovation programme under the Marie Skłodowska-Curie Grant Agreement No 101034413.
